### ISSUE TITLE
hope add filetree-show-cur-git-root to open current git repo root

### ISSUE THREAD

**Issue by futurist** [knpatel401/filetree#11] opened 2021-11-27 13:54 UTC
Some thing like below can find root dir of current git repo:

```sh
git rev-parse --show-toplevel
```

Is it possible to add a command like `filetree-show-cur-git-root` to open current git repo root?

**Comment by knpatel401** [comment] 2021-11-27 17:51
Hi @futurist 

Yes, that's a good idea--thanks for the suggestion.  I'll plan to add this functionality.

Thanks!
Ketan

**Comment by knpatel401** [comment] 2021-11-27 19:19
Hi @futurist,

The latest commit ([18a75836](https://github.com/knpatel401/filetree/commit/18a75836d245b873f29feab81768c4e57e05173b)) adds the command *filetree-show-vc-dir-recursively*, which will load the files (recursively) under the version control root directory of the current buffer.  The command loads all the files under the vc root and puts the list on the stack, then it filters to only the files under version control and puts that on the stack--that's what you'll see in the file tree after running the command.  If you want all the files (rather than just the files under version control, type "b" to pop the stack after running the command).

The command can be run either from a file buffer or from dired (currently not supported from an eshell buffer).  

Please let me know if you see any issues.

Thanks!
Ketan

**Comment by futurist** [comment] 2021-11-28 00:40
Open some file in a repo, then I run `filetree-show-vc-dir-recursively`, it gives me below message

```
if: Not a version controlled repo
```

**Comment by knpatel401** [comment] 2021-11-28 02:24
Thanks for the feedback.  

I'm not sure why vc-root-dir is failing where magit-toplevel returns the right dir.  I'll dig into it a little more and also try to reproduce the issue locally to debug it further.  

In the meantime, I checked in a change [5a30023c](https://github.com/knpatel401/filetree/commit/5a30023c897f0f93ec90f84caed8752b4ac98418) so that we check magit-toplevel if vc-root-dir fails.  I'm still using vc-backend to filter the file list for those that are part of the repo, so not sure whether or not that will work in your case.  If you happen to get a chance, could you please try out this change to see if the change works for your scenario?

Thanks!
Ketan

**Comment by knpatel401** [comment] 2022-02-11 04:07
Closing this for now since the current work-around should address the cases where vc-root-dir fails.

**Closed by knpatel401** 2022-02-11 04:07 UTC
Labels: enhancement
